name: Python Automation with Processed Tokens Persistence

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 最大运行时间10分钟
    
    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v4  # 使用最新版本
      with:
        fetch-depth: 1  # 只获取最近一次提交
    
    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 使用稳定版本
        cache: 'pip'  # 缓存依赖
    
    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --quiet  # 静默安装
    
    # Step 4: 拉取最新的 processed_tokens.json
    - name: Pull latest processed_tokens.json
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin main || echo "No changes to pull"
    
    # Step 5: 运行 Python 脚本
    - name: Run Python script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      continue-on-error: false
      run: |
        python main.py || exit 1
    
    # Step 6: 提交并推送更新的 processed_tokens.json
    - name: Commit and push processed_tokens.json
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add processed_tokens.json
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Update processed_tokens.json' && git push)
